### ISSUE TITLE
插入视频url的问题

### ISSUE THREAD

**Issue by troyliu0105** [geekplux/hexo-tag-video#1]
如果把iframe里面的src换成自己的视频连接的话，每次打开都会自动播放。怎么可以让他手动播放啊？ 查了好多资料都找不到答案。用video元素代替iframe也不可以

**Comment by geekplux** [comment]
每个视频网站的通用代码不同，所以应该是直接替换整个 iframe，不是替换里面的链接。

**Comment by troyliu0105** [comment]
可能您误解我的意思了。详细情况是这样的。我有一个mp4视频上传到了七牛的空间里，然后就得到了一个视频的url。之前我是直接通过<video>标签来插入的，可以正常显示，并且可以设置不启用自动播放，但是缺点就是不是响应式的。然后用了您的这个插件，我把你给的模板代码里面的iframe的src直接替换成了我的视频地址，并且是响应的，但是却总是会自动播放。==。。。。用video标签替换iframe标签也不可以（完全显示不出来）

**Comment by geekplux** [comment]
你得上传到优酷，土豆这种视频网站上。然后用视频下方的「通用代码」。上传都七牛我没试过，看来是不行。

**Comment by geekplux** [comment]
只能用iframe标签，你可以上传到优酷，土豆这种视频网站上。上传都七牛我没试过，看来是不行。
