### ISSUE TITLE
没用啊

### ISSUE THREAD

**Issue by LiuGuoGY** [geekplux/hexo-tag-video#2]
hexo 3.3
没有任何效果

**Comment by geekplux** [comment]
什么是没有效果？你可以稍微说清楚点。把你使用的方法贴出来之类的

**Comment by LiuGuoGY** [comment]
就是说，前面都配置好了，但是贴上你的example，网页没有任何显示。现在没法贴给你看，晚上贴给你看，我想要的是能自适应大小的插入优酷等视频网站的视频。

**Comment by geekplux** [comment]
嗯，晚上你贴了我再看看

**Comment by LiuGuoGY** [comment]
@geekplux 好的

**Comment by LiuGuoGY** [comment]
@geekplux 
安装
```
Administrator@DESKTOP-ARNFU1L MINGW64 /f/Hexo (master)
$ npm install hexo-tag-video --save
added 1 package in 20.729s
```
使用
```
{% video '<iframe height=498 width=510 src="https://player.youku.com/embed/XNTkyMTM0MzY4" frameborder=0 allowfullscreen></iframe>' %}
```
![Uploading QQ截图201
![qq 20170619220138](https://user-images.githubusercontent.com/24603342/27289224-bf584bfa-553b-11e7-83a6-a7dd9f493d74.png)
![qq 20170619220247](https://user-images.githubusercontent.com/24603342/27289225-bf60a98a-553b-11e7-9fed-cb79da70256d.png)

70619220138.png…]()
![qq 20170619220247](https://user-images.githubusercontent.com/24603342/27289225-bf60a98a-553b-11e7-9fed-cb79da70256d.png)

网页无显示

**Comment by geekplux** [comment]
我刚试了下，是 youku 的 <iframe> 通用代码放不出视频了，之前是可以的。
我有空改进一下，让这个插件支持 <embed> 引入视频。

**Comment by LiuGuoGY** [comment]
好的，谢谢！其他视频网站的可以吗？

**Comment by geekplux** [comment]
我在写这个插件的时候优酷、土豆、搜狐都行。现在。。好像大家都用 B 站和优酷了2333，等我改成 <embed>  之后，这俩应该就可以了。

**Comment by LiuGuoGY** [comment]
@geekplux 好的，谢谢！

**Comment by zzlw** [comment]
好吧
