### ISSUE TITLE
example中的示例无效

### ISSUE THREAD

**Issue by tlemar** [geekplux/hexo-tag-video#3]
删除掉单引号正常 

{% video <iframe height=498 width=510 src="http://player.youku.com/embed/XNTkyMTM0MzY4" frameborder=0 allowfullscreen></iframe> %}  

hexo环境：
hexo: 3.4.2
hexo-cli: 1.0.4
os: Linux 4.4.0-63-generic linux x64
http_parser: 2.7.0
node: 8.4.0
v8: 6.0.286.52
uv: 1.13.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.22.0
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b

**Comment by Logan1x** [comment]
@tlemar  Thank you for pasting issue here I was trying with quotes instead. @geekplux please solve this issue.
